/**
 *
 * $Id$
 */
package bpmn.validation;

import bpmn.NatureActivityMaker;
import bpmn.PerformanceActivityMaker;
import bpmn.TypeActivity;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn.Activity}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityValidator {
	boolean validate();

	boolean validateType(TypeActivity value);

	boolean validateNature(NatureActivityMaker value);

	boolean validatePerformance(EList<PerformanceActivityMaker> value);

	boolean validateNatureactivitymaker(NatureActivityMaker value);

	boolean validatePerformanceactivitymaker(EList<PerformanceActivityMaker> value);
}
