/**
 *
 * $Id$
 */
package bpmn.validation;

import bpmn.Swimlane;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn.BPMN}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNValidator {
	boolean validate();

	boolean validateNameDiagram(String value);

	boolean validateSwimlane(EList<Swimlane> value);
}
