/**
 *
 * $Id$
 */
package bpmn.validation;

import bpmn.Figure;

/**
 * A sample validator interface for {@link bpmn.Connection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConnectionValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateTo(Figure value);

	boolean validateFrom(Figure value);
}
