/**
 *
 * $Id$
 */
package bpmn.validation;

import bpmn.Figure;
import bpmn.Pool;
import bpmn.Swimlane;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn.Lane}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LaneValidator {
	boolean validate();

	boolean validateNameLane(String value);

	boolean validateFigure(EList<Figure> value);

	boolean validatePoolrelationlane(Pool value);

	boolean validateLaneincludefigure(EList<Figure> value);

	boolean validateLanerelationswimline(Swimlane value);
}
