/**
 *
 * $Id$
 */
package bpmn.validation;

import bpmn.Lane;
import bpmn.Pool;
import bpmn.Swimlane;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link bpmn.Pool}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PoolValidator {
	boolean validate();

	boolean validateNamePool(String value);

	boolean validateSwimlane(Swimlane value);

	boolean validateLanerelationpool(EList<Lane> value);

	boolean validateChildpool(EList<Pool> value);

	boolean validateFatherpool(Pool value);
}
